[package]
name = "geohack"
version = "0.1.1"
edition = "2024"

[dependencies]
mimalloc = { version = "0.1", features = ["secure"] }
reqwest = { version = "*", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
axum = { version = "*", features = [
	"http1",
	"http2",
	"tokio",
	"json",
	"macros",
] }
tracing = "*"
tracing-subscriber = "*"
tower-http = { version = "*", features = ["full"] }
anyhow = "*"
moka = { version = "0.12", features = ["future"] }
utm = "0.1.6"
lonlat_bng = "0.9.0"
urlencoding = "*"
html-escape = "*"
regex = "*"
aho-corasick = "1"

[dev-dependencies]

[profile.release]
opt-level = 3
lto = 'fat'
panic = 'abort'
codegen-units = 1
